build:
  image: docker:latest
  services:
  - docker:dind
  variables:
    CI_APPLICATION_REPOSITORY: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG
    CI_APPLICATION_TAG: $CI_COMMIT_SHA
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build -t ${CI_APPLICATION_REPOSITORY}:${CI_APPLICATION_TAG} .
    - docker push ${CI_APPLICATION_REPOSITORY}:${CI_APPLICATION_TAG}

    # if branch is not main push a latest image to registry/branch to have a latest in the branch
    - if [ "$CI_COMMIT_REF_NAME" != "main" ]; then docker tag ${CI_APPLICATION_REPOSITORY}:${CI_APPLICATION_TAG} ${CI_APPLICATION_REPOSITORY}:latest ; docker push ${CI_APPLICATION_REPOSITORY}:latest ; fi

    # if branch is main push to main latest
    - if [ "$CI_COMMIT_REF_NAME" = "main" ]; then docker tag ${CI_APPLICATION_REPOSITORY}:${CI_APPLICATION_TAG} ${CI_REGISTRY_IMAGE}:latest ; docker push ${CI_REGISTRY_IMAGE}:latest ; fi

    # if branch is main push to dockerhub and create an extra timestamped tag
    - docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASS}
    - export DATE_NOW=$(date +%s)
    - docker tag ${CI_APPLICATION_REPOSITORY}:${CI_APPLICATION_TAG} aapjeisbaas/semaphore:latest
    - docker tag ${CI_APPLICATION_REPOSITORY}:${CI_APPLICATION_TAG} aapjeisbaas/semaphore:${DATE_NOW}
    - if [ "$CI_COMMIT_REF_NAME" = "main" ]; then docker push aapjeisbaas/semaphore:latest ; fi
    - if [ "$CI_COMMIT_REF_NAME" = "main" ]; then docker push aapjeisbaas/semaphore:${DATE_NOW} ; fi
